import type { Cell, GemColor, Level } from './game/types'

const makeCell = (x: number, y: number, targetColor: GemColor, gemColor?: GemColor): Cell => ({
  id: `${x},${y}`,
  x,
  y,
  targetColor,
  gemColor,
})

const makeLevel = (
  id: number,
  title: string,
  timeLimitSeconds: number,
  specs: Array<[number, number, GemColor, GemColor?]>,
): Level => ({
  id,
  title,
  timeLimitSeconds,
  cells: specs.map(([x, y, targetColor, gemColor]) => makeCell(x, y, targetColor, gemColor)),
})

export const levels: Level[] = [
  makeLevel(1, '第1关', 300, [
    [1, 0, 'red', 'blue'],
    [2, 0, 'red', 'blue'],
    [7, 0, 'blue', 'red'],
    [8, 0, 'blue', 'red'],
    [0, 1, 'red', 'blue'],
    [1, 1, 'red', 'blue'],
    [2, 1, 'red', 'blue'],
    [3, 1, 'red', 'blue'],
    [5, 1, 'blue', 'red'],
    [6, 1, 'blue', 'red'],
    [7, 1, 'blue', 'red'],
    [8, 1, 'blue', 'red'],
    [9, 1, 'blue', 'red'],
    [1, 2, 'red', 'blue'],
    [2, 2, 'red', 'blue'],
    [3, 2, 'red', 'blue'],
    [4, 2, 'red', 'blue'],
    [5, 2, 'blue', 'red'],
    [6, 2, 'blue', 'red'],
    [7, 2, 'blue', 'red'],
    [8, 2, 'blue', 'red'],
    [2, 3, 'red', 'blue'],
    [3, 3, 'red', 'blue'],
    [4, 3, 'red', 'red'],
    [5, 3, 'blue', 'red'],
    [6, 3, 'blue', 'red'],
    [5, 4, 'red', 'blue'],
    [5, 5, 'red', 'red'],
  ]),
  makeLevel(2, '第2关 小屋', 300, [
    [3, 0, 'red', 'red'],
    [4, 0, 'red', 'red'],
    [5, 0, 'red', 'red'],
    [2, 1, 'red', 'yellow'],
    [3, 1, 'yellow', 'yellow'],
    [4, 1, 'yellow', 'yellow'],
    [5, 1, 'yellow', 'red'],
    [6, 1, 'red', 'red'],
    [1, 2, 'red', 'yellow'],
    [2, 2, 'yellow', 'green'],
    [3, 2, 'green', 'green'],
    [4, 2, 'green', 'green'],
    [5, 2, 'green', 'yellow'],
    [6, 2, 'yellow', 'red'],
    [7, 2, 'red', 'blue'],
    [2, 3, 'blue', 'green'],
    [3, 3, 'green', 'purple'],
    [4, 3, 'purple', 'green'],
    [5, 3, 'green', 'blue'],
    [6, 3, 'blue', 'blue'],
    [2, 4, 'blue', 'blue'],
    [3, 4, 'blue', 'purple'],
    [4, 4, 'purple', 'blue'],
    [5, 4, 'blue', 'blue'],
    [6, 4, 'blue', 'blue'],
    [4, 5, 'blue', 'blue'],
    [1, 5, 'blue', 'green'],
    [2, 5, 'green', 'green'],
    [6, 5, 'green', 'blue'],
    [7, 5, 'blue', 'red'],
  ]),
  makeLevel(3, '第3关 茶杯', 300, [
    [2, 0, 'yellow', 'yellow'],
    [3, 0, 'yellow', 'yellow'],
    [4, 0, 'yellow', 'yellow'],
    [5, 0, 'yellow', 'yellow'],
    [6, 0, 'yellow', 'blue'],
    [1, 1, 'blue', 'blue'],
    [2, 1, 'blue', 'green'],
    [3, 1, 'green', 'green'],
    [4, 1, 'green', 'green'],
    [5, 1, 'green', 'blue'],
    [6, 1, 'blue', 'blue'],
    [7, 1, 'blue', 'blue'],
    [1, 2, 'blue', 'blue'],
    [2, 2, 'blue', 'green'],
    [3, 2, 'green', 'purple'],
    [4, 2, 'purple', 'green'],
    [5, 2, 'green', 'blue'],
    [6, 2, 'blue', 'blue'],
    [7, 2, 'blue', 'blue'],
    [2, 3, 'blue', 'blue'],
    [3, 3, 'blue', 'blue'],
    [4, 3, 'blue', 'blue'],
    [5, 3, 'blue', 'blue'],
    [6, 3, 'blue', 'red'],
    [7, 3, 'red', 'red'],
    [8, 3, 'red', 'red'],
    [7, 4, 'red', 'red'],
    [8, 4, 'red', 'purple'],
    [3, 5, 'purple', 'purple'],
    [6, 5, 'purple', 'red'],
    [3, 6, 'red', 'blue'],
    [4, 6, 'blue', 'blue'],
    [5, 6, 'blue', 'red'],
    [6, 6, 'red', 'yellow'],
  ]),
  makeLevel(4, '第4关 台灯', 300, [
    [3, 0, 'yellow', 'yellow'],
    [4, 0, 'yellow', 'yellow'],
    [5, 0, 'yellow', 'yellow'],
    [2, 1, 'yellow', 'red'],
    [3, 1, 'red', 'red'],
    [4, 1, 'red', 'red'],
    [5, 1, 'red', 'yellow'],
    [6, 1, 'yellow', 'yellow'],
    [2, 2, 'yellow', 'red'],
    [3, 2, 'red', 'red'],
    [4, 2, 'red', 'red'],
    [5, 2, 'red', 'yellow'],
    [6, 2, 'yellow', 'green'],
    [3, 3, 'green', 'green'],
    [4, 3, 'green', 'green'],
    [5, 3, 'green', 'green'],
    [4, 4, 'green', 'purple'],
    [3, 5, 'purple', 'purple'],
    [4, 5, 'purple', 'purple'],
    [5, 5, 'purple', 'blue'],
    [2, 6, 'blue', 'blue'],
    [3, 6, 'blue', 'blue'],
    [4, 6, 'blue', 'blue'],
    [5, 6, 'blue', 'blue'],
    [6, 6, 'blue', 'blue'],
    [1, 7, 'blue', 'blue'],
    [2, 7, 'blue', 'purple'],
    [3, 7, 'purple', 'purple'],
    [4, 7, 'purple', 'purple'],
    [5, 7, 'purple', 'blue'],
    [6, 7, 'blue', 'blue'],
    [7, 7, 'blue', 'blue'],
    [3, 8, 'blue', 'blue'],
    [5, 8, 'blue', 'blue'],
    [2, 8, 'blue', 'purple'],
    [4, 8, 'purple', 'blue'],
    [6, 8, 'blue', 'purple'],
    [4, 9, 'purple', 'yellow'],
  ]),
  makeLevel(5, '第5关 礼物相框', 300, [
    [1, 0, 'red', 'red'],
    [2, 0, 'red', 'yellow'],
    [3, 0, 'yellow', 'yellow'],
    [4, 0, 'yellow', 'red'],
    [5, 0, 'red', 'red'],
    [6, 0, 'red', 'red'],
    [1, 1, 'red', 'purple'],
    [2, 1, 'purple', 'yellow'],
    [3, 1, 'yellow', 'yellow'],
    [4, 1, 'yellow', 'purple'],
    [5, 1, 'purple', 'red'],
    [6, 1, 'red', 'blue'],
    [0, 2, 'blue', 'blue'],
    [1, 2, 'blue', 'green'],
    [2, 2, 'green', 'green'],
    [3, 2, 'green', 'green'],
    [4, 2, 'green', 'green'],
    [5, 2, 'green', 'blue'],
    [6, 2, 'blue', 'blue'],
    [7, 2, 'blue', 'blue'],
    [0, 3, 'blue', 'green'],
    [1, 3, 'green', 'purple'],
    [2, 3, 'purple', 'green'],
    [3, 3, 'green', 'green'],
    [4, 3, 'green', 'purple'],
    [5, 3, 'purple', 'green'],
    [6, 3, 'green', 'blue'],
    [7, 3, 'blue', 'blue'],
    [1, 4, 'blue', 'blue'],
    [2, 4, 'blue', 'red'],
    [3, 4, 'red', 'red'],
    [4, 4, 'red', 'blue'],
    [5, 4, 'blue', 'blue'],
    [6, 4, 'blue', 'red'],
    [2, 5, 'red', 'red'],
    [3, 5, 'red', 'red'],
    [4, 5, 'red', 'red'],
    [5, 5, 'red', 'red'],
    [1, 5, 'red', 'red'],
    [6, 5, 'red', 'yellow'],
    [3, 6, 'yellow', 'yellow'],
    [4, 6, 'yellow', 'red'],
  ]),
  makeLevel(6, '第6关 温馨客厅', 300, [
    [1, 0, 'yellow', 'yellow'],
    [2, 0, 'yellow', 'red'],
    [6, 0, 'red', 'red'],
    [7, 0, 'red', 'yellow'],
    [0, 1, 'yellow', 'green'],
    [1, 1, 'green', 'green'],
    [2, 1, 'green', 'yellow'],
    [3, 1, 'yellow', 'red'],
    [5, 1, 'red', 'purple'],
    [6, 1, 'purple', 'purple'],
    [7, 1, 'purple', 'red'],
    [8, 1, 'red', 'blue'],
    [0, 2, 'blue', 'green'],
    [1, 2, 'green', 'purple'],
    [2, 2, 'purple', 'green'],
    [3, 2, 'green', 'blue'],
    [5, 2, 'blue', 'red'],
    [6, 2, 'red', 'red'],
    [7, 2, 'red', 'blue'],
    [8, 2, 'blue', 'blue'],
    [1, 3, 'blue', 'blue'],
    [2, 3, 'blue', 'blue'],
    [6, 3, 'blue', 'blue'],
    [7, 3, 'blue', 'red'],
    [0, 4, 'red', 'red'],
    [1, 4, 'red', 'green'],
    [2, 4, 'green', 'green'],
    [3, 4, 'green', 'green'],
    [4, 4, 'green', 'green'],
    [5, 4, 'green', 'red'],
    [6, 4, 'red', 'red'],
    [7, 4, 'red', 'red'],
    [8, 4, 'red', 'red'],
    [1, 5, 'red', 'purple'],
    [2, 5, 'purple', 'blue'],
    [3, 5, 'blue', 'blue'],
    [4, 5, 'blue', 'blue'],
    [5, 5, 'blue', 'purple'],
    [6, 5, 'purple', 'red'],
    [7, 5, 'red', 'yellow'],
    [2, 6, 'yellow', 'yellow'],
    [6, 6, 'yellow', 'blue'],
    [0, 6, 'blue', 'red'],
    [1, 6, 'red', 'red'],
    [7, 6, 'red', 'blue'],
    [8, 6, 'blue', 'yellow'],
  ]),
]

export function validateLevel(level: Level): string[] {
  const errors: string[] = []
  const targetCounts = countColors(level.cells.map(({ targetColor }) => targetColor))
  const gemCounts = countColors(level.cells.map(({ gemColor }) => gemColor).filter(Boolean) as GemColor[])

  for (const color of Object.keys(targetCounts) as GemColor[]) {
    if (targetCounts[color] !== gemCounts[color]) {
      errors.push(`${level.title} ${color} target count ${targetCounts[color]} does not match gem count ${gemCounts[color] ?? 0}`)
    }
  }

  for (const color of Object.keys(gemCounts) as GemColor[]) {
    if (targetCounts[color] !== gemCounts[color]) {
      errors.push(`${level.title} ${color} gem count ${gemCounts[color]} does not match target count ${targetCounts[color] ?? 0}`)
    }
  }

  return errors
}

function countColors(colors: GemColor[]): Partial<Record<GemColor, number>> {
  return colors.reduce<Partial<Record<GemColor, number>>>((counts, color) => {
    counts[color] = (counts[color] ?? 0) + 1
    return counts
  }, {})
}
